list_of_cousins = [
    "The Prince",
    "Lalala",
    "Nik",
    "Ace",
    "Johnson",
    "Velvet",
    "Fujio",
    "Havana",
    "Peso",
    "Shikao",
    "Odeko",
    "Honey",
    "Marny",
    "Kuro",
    "Foomin",
    "June",
    "Ichigo",
    "Marcy",
    "Njamo",
    "Dipp",
    "Opeo",
    "Nickel",
    "Jungle",
    "Miso",
    "Twinkle",
    "Huey",
    "Nutsuo",
    "Beyond",
    "Kinoko",
    "Macho",
    "L'Amour",
    "Daisy",
    "Lucha",
    "Miki",
    "Odeon",
    "Can-Can",
    "Shy",
    "Slip",
    "Drooby",
    "Signolo"
]

cousins_items = {}
cousin_id = 0
for cousin in list_of_cousins:
    cousins_items.update({cousin: {"ID": cousin_id, "classification": "something"}})
    cousin_id += 1

list_of_presents = [
    "Headphones",
    "Crown",
    "Giraffe Hat",
    "Ribbons",
    "Flower",
    "Little Buddy",
    "Mt. Fuji",
    "Mushroom",
    "Antenna",
    "Peacock Feathers",
    "Horsey",
    "Bikini",
    "Camera",
    "Pochette",
    "Scarf",
    "Guitar",
    "Cool Belt",
    "Moustache",
    "Trumpet",
    "Glasses",
    "Wig",
    "Royal Mask",
    "Mask",
    "Bunny Ears",
    "Long Nose",
    "Pencil",
    "Tutu",
    "Tire",
    "Singlet",
    "Note Glasses",
    "Little Prince",
    "Little King"
]


fans_and_cousins_logic = {
    "Rainbow Girl": ["Macho"],
    "Lazybones": ["Can-Can", "Havana"],
    "Grandpa": ["Johnson", "Twinkle", "Kuro"],
    "Grandma": ["Foomin", "Miki", "Velvet"],
    "Bird & Elephant": ["Shikao", "Lucha", "Nutsuo", "Drooby"],
    "Dog": [],
    "Soccer Kid": ["Ace", "Slip"],
    "Ikebana Teacher": ["Ichigo"],
    "Substitute Teacher": ["Miso", "Huey"],
    "F1 Racer": ["Odeko", "Shy", "Nickel"],
    "Rain Coat Girl": ["June", "Fujio"],
    "Dr. Katamari": ["Beyond", "Njamo"],
    "Crane Hat Boy": ["Opeo"],
    "Just-Right Girl": ["Marcy", "Peso", "Signolo"],
    "Cowbear Farmer": ["Daisy"],
    "Excited Baby": ["Jungle"],
    "Cleanly Mom": ["L'Amour"],
    "Fund-raiser": ["Odeon"],
    "Hansel & Gretel": ["Honey"],
    "Float Boy": ["Marny"],
    "Camper Man": ["Kinoko"],
    "Mini-Sumo": ["Nik"],
    "Snow Child": ["Lalala"],
    "Book Worm": ["Dipp"],
    "Tomio Hoshino": [],
    "Mutsuo Hoshino": []
}

for fan in fans_and_cousins_logic:
    print(fan)